import Link from "next/link"
import { ArrowLeft } from "lucide-react"

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-8">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-gray-600 hover:text-gray-900 mb-6 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to home
        </Link>

        <div className="bg-white rounded-lg shadow-sm p-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
          <p className="text-sm text-gray-600 mb-8">Effective Date: May 2, 2026</p>

          <div className="prose prose-sm max-w-none">
            <p className="mb-4">
              <strong>Company Name:</strong> Guildy.ai, Inc.
            </p>
            <p className="mb-4">
              <strong>Product/App:</strong> Guildy.ai
            </p>
            <p className="mb-4">
              <strong>Website:</strong>{" "}
              <a href="https://guildy.ai" className="text-blue-600 hover:underline">
                https://guildy.ai
              </a>
            </p>
            <p className="mb-4">
              <strong>Contact Email:</strong>{" "}
              <a href="mailto:support@guildy.ai" className="text-blue-600 hover:underline">
                support@guildy.ai
              </a>
            </p>
            <p className="mb-6">
              <strong>Business Address:</strong> Guildy.ai, Inc., San Francisco, CA, USA
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Introduction</h2>
            <p className="mb-4">
              Guildy is a job pipeline tracker with AI-powered interview prep. This Privacy Policy
              explains how we collect, use, store, and protect your information.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Data We Collect</h2>
            <p className="mb-2">When you use Guildy, we collect:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Account info (email address used for sign-in)</li>
              <li>Resume or background text you upload or paste</li>
              <li>Job entries you create (company name, role title, JD, latest message, notes)</li>
              <li>Interview prep generated by Guildy on your behalf</li>
            </ul>
            <p className="mb-4">
              We do not access your email inbox, calendar, or any other Google service. Sign-in is
              by magic link only.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Purpose of Data Use</h2>
            <p className="mb-2">We use your data to:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Authenticate you and maintain your session</li>
              <li>Generate interview prep tailored to your background and the role</li>
              <li>Display your pipeline and prep history inside Guildy</li>
            </ul>
            <p className="mb-2">We do not use your data for:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Advertising or marketing</li>
              <li>Profiling unrelated to job-search assistance</li>
              <li>Data sales or brokerage</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">AI &amp; Machine Learning</h2>
            <p className="mb-2">
              Guildy sends your resume, the job context you provide, and any pasted notes to AI
              models to:
            </p>
            <ul className="list-disc pl-6 mb-4">
              <li>Generate interview prep, likely questions, and draft answers</li>
              <li>Summarize public company and interviewer information (paid tier only)</li>
            </ul>
            <p className="mb-4">
              We require all AI vendors to not train on your data.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Storage &amp; Retention</h2>
            <p className="mb-4">
              Your data is stored on Supabase (Postgres) with row-level security restricting
              access to your account only. Resume PDFs are stored in a private bucket and accessed
              via signed URLs.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Security</h2>
            <p className="mb-2">We implement strong security measures, including:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>TLS encryption in transit</li>
              <li>Encrypted data storage</li>
              <li>Per-user row-level security policies</li>
              <li>Secure secrets management</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">User Controls</h2>
            <p className="mb-2">You may:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Update or replace your resume in settings</li>
              <li>Delete individual jobs from your pipeline</li>
              <li>Email support@guildy.ai to request full account deletion</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Children&apos;s Privacy</h2>
            <ul className="list-disc pl-6 mb-4">
              <li>Guildy is not intended for children under 16.</li>
              <li>We do not knowingly collect data from children.</li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Changes to This Policy</h2>
            <p className="mb-4">
              We may update this policy. Updates will be posted here with a new effective date.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Contact Us</h2>
            <p className="mb-2">Guildy.ai, Inc.</p>
            <p className="mb-2">San Francisco, CA, USA</p>
            <p className="mb-4">
              <a href="mailto:support@guildy.ai" className="text-blue-600 hover:underline">
                support@guildy.ai
              </a>
            </p>
            <p className="mb-4">By using Guildy, you agree to this Privacy Policy.</p>
          </div>
        </div>
      </div>
    </div>
  )
}
