// Fake pipeline data for demo recordings.
// Returned by GET /api/pipelines when DEMO_MODE = true in that route.

export const DEMO_PIPELINES = [
  {
    id: "demo-1",
    company: "Horizon Labs",
    role: "Senior Software Engineer",
    stage: "FULL_LOOP",
    stage_detail: "On-site loop scheduled with 4 engineers and the VP of Engineering",
    status: "WAITING",
    last_email_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    last_email_subject: "Interview Loop Confirmed — Horizon Labs",
    last_email_from_name: "Sarah Chen (Recruiting)",
    last_email_from_email: "recruiting@horizonlabs.io",
    last_email_snippet: "Hi, we're excited to confirm your on-site loop for next Thursday...",
    predicted_stages: ["Recruiter Screen", "Hiring Manager", "Technical", "Full Loop", "Offer"],
    prep_json: JSON.stringify({
      stageFocus: "Full Loop — 4-panel technical + culture interviews",
      companyIntel: {
        industry: "Infrastructure / DevTools",
        size: "Series B, ~120 employees",
        hqLocation: "San Francisco, CA",
        summary: "Horizon Labs builds developer infrastructure for distributed systems. Recently raised $40M Series B led by Andreessen Horowitz.",
        product: "Real-time observability platform used by 500+ engineering teams",
        businessModel: "SaaS, usage-based pricing",
        competitors: ["Datadog", "New Relic", "Grafana"],
        techStack: "Go, Kubernetes, React, PostgreSQL, ClickHouse",
        culture: "Strong eng culture, ship fast, high ownership",
        recentNews: ["Series B announcement", "Partnership with AWS"],
      },
      interviewStrategy: {
        goalForThisStage: "Demonstrate system design depth and collaborative problem-solving",
        whatTheyEvaluate: ["Systems thinking", "Communication under pressure", "Code quality"],
        howToSucceed: ["Think aloud through every tradeoff", "Ask clarifying questions before coding", "Reference real examples from past work"],
        commonMistakes: ["Over-engineering the solution", "Going silent during tough questions"],
        answerLength: "Concise for behavioral (2 min), thorough for technical (10–15 min)",
      },
      questionsTheyMightAsk: [
        { question: "Design a distributed rate limiter that handles 1M requests/sec", category: "System Design" },
        { question: "Walk me through a time you had to make a hard architectural call under time pressure", category: "Behavioral" },
        { question: "How would you debug a latency spike in a microservices environment?", category: "Technical" },
        { question: "Tell me about a project you'd do differently in hindsight", category: "Behavioral" },
      ],
      questionsYouShouldAsk: [
        { question: "What does the on-call rotation look like for this team?", category: "Team" },
        { question: "What's the biggest technical challenge the team is facing right now?", category: "Technical" },
        { question: "How do you measure engineering success here?", category: "Culture" },
      ],
      prepChecklist: [
        "Review CAP theorem and consistency models",
        "Prep 3 STAR stories: ownership, conflict, failure",
        "Read the Horizon Labs engineering blog (2 recent posts)",
        "Review your distributed systems projects",
      ],
    }),
  },
  {
    id: "demo-2",
    company: "Apex Systems",
    role: "Staff Engineer",
    stage: "OFFER_DISCUSSION",
    stage_detail: "Verbal offer extended, negotiation in progress",
    status: "WAITING",
    last_email_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    last_email_subject: "RE: Offer Details — Apex Systems",
    last_email_from_name: "Marcus Reid",
    last_email_from_email: "mreid@apexsystems.com",
    last_email_snippet: "We're thrilled to move forward. Please review the attached offer and let us know if you have questions...",
    predicted_stages: ["Phone Screen", "Technical", "System Design", "Executive", "Offer"],
    prep_json: JSON.stringify({
      stageFocus: "Offer negotiation — comp benchmarking and leverage",
      companyIntel: {
        industry: "FinTech / Payments",
        size: "Series D, ~400 employees",
        hqLocation: "New York, NY",
        summary: "Apex Systems provides real-time payment infrastructure for enterprise banks and fintechs. Processing $2B+ in daily volume.",
        product: "Payment orchestration layer and fraud detection platform",
        businessModel: "Transaction-based fees + enterprise SaaS",
        competitors: ["Stripe", "Adyen", "Braintree"],
        techStack: "Java, Kafka, Redis, PostgreSQL, AWS",
        culture: "Fast-paced, data-driven, results over process",
        recentNews: ["Series D close at $180M", "Expansion into EU markets"],
      },
      compensationIntel: {
        salaryRange: "$220K–$260K base for Staff level in NYC",
        equityInfo: "Typical Series D grant: 0.05–0.1% over 4 years",
        negotiationTips: ["Counter at least 10% above verbal offer", "Ask about accelerated vesting", "Request sign-on to offset unvested equity"],
        whenToDiscuss: "After verbal — ask for full written offer before final negotiation",
      },
      questionsYouShouldAsk: [
        { question: "What's the standard refresh grant cadence?", category: "Compensation" },
        { question: "Is there flexibility on the sign-on given unvested equity I'm leaving behind?", category: "Negotiation" },
      ],
      prepChecklist: [
        "Pull Levels.fyi comps for Staff Eng in NYC at Series D",
        "Calculate unvested equity you'd be leaving",
        "Draft counter offer email",
      ],
    }),
  },
  {
    id: "demo-3",
    company: "Vertex AI",
    role: "Engineering Manager",
    stage: "HIRING_MANAGER",
    stage_detail: "Hiring manager screen scheduled for Wednesday",
    status: "WAITING",
    last_email_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    last_email_subject: "Interview Invite: Hiring Manager Round — Vertex AI",
    last_email_from_name: "Priya Nair (Talent)",
    last_email_from_email: "priya.nair@vertexai.co",
    last_email_snippet: "Hi! We'd love to set up a 45-minute conversation with Jordan, our VP of Engineering...",
    predicted_stages: ["Recruiter Screen", "HM Screen", "Panel", "Offer"],
    prep_json: JSON.stringify({
      stageFocus: "Hiring manager screen — fit, leadership style, team vision",
      companyIntel: {
        industry: "AI / ML Platform",
        size: "Series C, ~200 employees",
        hqLocation: "Seattle, WA",
        summary: "Vertex AI (not Google) builds fine-tuning and deployment tooling for enterprise LLMs. Growing 3x YoY.",
        product: "LLM fine-tuning platform and model serving infrastructure",
        businessModel: "Consumption-based SaaS",
        competitors: ["Together AI", "Replicate", "Hugging Face"],
        techStack: "Python, PyTorch, Kubernetes, FastAPI, React",
        culture: "Research-meets-product, high technical bar, async-first",
        recentNews: ["Series C at $75M", "Partnership with Anthropic and Cohere"],
      },
      interviewStrategy: {
        goalForThisStage: "Show alignment with VP's vision and demonstrate people leadership depth",
        whatTheyEvaluate: ["Management philosophy", "How you handle underperformance", "Technical credibility alongside leadership"],
        howToSucceed: ["Ask about their current team challenges in the first 10 minutes", "Tell a story about growing an engineer into a senior role"],
        commonMistakes: ["Being too IC-focused", "Not having specific examples of conflict resolution"],
        answerLength: "2–3 minutes per behavioral, leave room for dialogue",
      },
      questionsTheyMightAsk: [
        { question: "How do you balance shipping velocity with technical debt?", category: "Leadership" },
        { question: "Tell me about a time you had to let someone go", category: "Behavioral" },
        { question: "How do you keep engineers motivated during a difficult quarter?", category: "Management" },
      ],
      questionsYouShouldAsk: [
        { question: "What does success look like for this team in the first 6 months?", category: "Role" },
        { question: "What's the biggest people challenge you're facing right now?", category: "Team" },
      ],
    }),
  },
  {
    id: "demo-4",
    company: "Nimbus Cloud",
    role: "Principal Engineer",
    stage: "PRESENTATION",
    stage_detail: "Take-home system design exercise submitted, awaiting technical review",
    status: "WAITING",
    last_email_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    last_email_subject: "Take-Home Exercise — Nimbus Cloud",
    last_email_from_name: "Alex Torres",
    last_email_from_email: "atorres@nimbuscloud.dev",
    last_email_snippet: "Thanks for submitting! Our team is reviewing your design doc and will follow up within 5 business days...",
    predicted_stages: ["Recruiter", "Technical Screen", "Take-Home", "System Design", "Offer"],
    prep_json: JSON.stringify({
      stageFocus: "Awaiting take-home review — prep for system design deep-dive",
      companyIntel: {
        industry: "Cloud Infrastructure",
        size: "Series B, ~80 employees",
        hqLocation: "Austin, TX",
        summary: "Nimbus Cloud offers a developer-friendly multi-cloud abstraction layer. Competes on simplicity and cost.",
        product: "Multi-cloud deployment orchestration and cost optimization",
        businessModel: "SaaS platform fee + cloud spend percentage",
        competitors: ["Terraform Cloud", "Pulumi", "Crossplane"],
        techStack: "Go, Rust, Kubernetes, Temporal, React",
        culture: "Small team, high ownership, everyone does infra",
        recentNews: ["SOC 2 Type II certified", "Launched GCP support"],
      },
      prepChecklist: [
        "Review your take-home submission — be ready to defend every decision",
        "Prep for 'why did you choose X over Y' questions",
        "Read their docs on multi-cloud networking approach",
      ],
    }),
  },
  {
    id: "demo-5",
    company: "Cascade Health",
    role: "Senior Frontend Engineer",
    stage: "SCREENING",
    stage_detail: "Initial recruiter screen completed, moving to technical round",
    status: "WAITING",
    last_email_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    last_email_subject: "Next Steps: Technical Interview — Cascade Health",
    last_email_from_name: "Jamie Liu",
    last_email_from_email: "jamie.liu@cascadehealth.io",
    last_email_snippet: "Great speaking with you! We'd like to schedule a 60-minute technical session with one of our senior engineers...",
    predicted_stages: ["Recruiter Screen", "Technical", "Team Interview", "Offer"],
    prep_json: JSON.stringify({
      stageFocus: "Technical coding round — React, TypeScript, accessibility",
      companyIntel: {
        industry: "Health Tech",
        size: "Series B, ~150 employees",
        hqLocation: "Portland, OR (remote-friendly)",
        summary: "Cascade Health builds care coordination software for mid-sized hospital networks. HIPAA-compliant platform with 300+ hospital clients.",
        product: "Patient intake, scheduling, and care team coordination tools",
        businessModel: "Per-seat SaaS + implementation services",
        competitors: ["Epic MyChart", "Phynd", "Kyruus"],
        techStack: "React, TypeScript, Next.js, GraphQL, PostgreSQL",
        culture: "Mission-driven, move fast but carefully (healthcare), strong work-life balance",
        recentNews: ["HIPAA BAA with three regional health systems", "Launched mobile patient app"],
      },
      interviewStrategy: {
        goalForThisStage: "Show clean, accessible React code and strong TypeScript fundamentals",
        whatTheyEvaluate: ["Component design", "State management reasoning", "Accessibility awareness", "Code clarity"],
        howToSucceed: ["Mention accessibility without being prompted", "Ask about their design system", "Write tests if time allows"],
        commonMistakes: ["Ignoring keyboard navigation", "Over-engineering small components"],
        answerLength: "Code speaks — narrate while you type",
      },
      questionsTheyMightAsk: [
        { question: "Build a filterable patient list component with search and pagination", category: "Coding" },
        { question: "How would you handle optimistic UI updates in a form-heavy app?", category: "Technical" },
        { question: "Walk me through how you'd approach accessibility for a complex data table", category: "Technical" },
      ],
      prepChecklist: [
        "Review React hooks patterns (useMemo, useCallback, useReducer)",
        "Practice a11y — ARIA roles, focus management",
        "Review TypeScript generics and type narrowing",
      ],
    }),
  },
]
