-- Migration to add missing columns to pipelines table
-- Run this in your Supabase SQL Editor

-- 1. Ensure columns exist
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS user_email TEXT; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS company TEXT; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS role TEXT; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS stage TEXT; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS stage_detail TEXT; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS last_email_subject TEXT; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS last_email_at TIMESTAMPTZ; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS last_email_from TEXT; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS last_email_from_name TEXT; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS last_email_snippet TEXT; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS insights_json JSONB; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS prep_json JSONB; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'WAITING'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS notes TEXT; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pipelines ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(); EXCEPTION WHEN others THEN NULL; END $$;

-- 2. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_pipelines_user_email ON pipelines(user_email);
CREATE INDEX IF NOT EXISTS idx_pipelines_last_email_at ON pipelines(last_email_at DESC);
